sudo: required
language: java
services:
- docker
cache:
  directories:
  - "$HOME/.m2"
install: true
jobs:
  include:
  - stage: Compilation and Installation
    script: scripts/travis.sh install
  - stage: Deploy on
    script: if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then bash scripts/travis.sh deploy; 
      fi
env:
  global:
  - secure: CXqLkLlvrx1fZjhMkMKmfiNNrMqZ4SntAkLgMyrpJ9q+Cn0YMFt/HvP3ygtn5CcGA4lx9hm6fYgt1PLJzYJVFhGPbrFeTFz+/LZCK9g7nG+3bWXap7xvHcFYDNPVvhogWM9RtNd4x2VTc/mwF22jwJdrHFFcDGOS11+CMnv+vBEvgsneaMw6uBslIYa0ZJqrKmQgTllmIRU5dy00VojDyYUvs6HwZHzCWRQvT7dIOTTZl/CZte8pN3iht5RxuI056cAXFZ4iMpvJYQUoZx05bCMZSm4kQf9FyyCk3cskjhASOkb8x66YnyFbHYGf95sAJzb7Zd/ae3FON0MbIP8q8U4C6QkOolxiZj0SjVaXRdYY+RQrnbel8odVo/W2wOrbcosAM9vs9kq59Dsac0sYae38pHRXNuXBIASXwsCRZ/l+Jmf0XlYwV5lhSpp15RyvnacFoWG77rbyOVGRCW9xjHFG6OdSiXWvS1XeHlc4A3RYXla2VH0WSCvKUYx0hwkkCscT+Ynevp2aVRWgGt/N/cvCHEThHAelddp0l9rc+S7FeiOO6nJaCC1bd9diSPR2/wQC90OD3Ddf1bHesxqpuAM8y54ZTHqYB/1jx3lhZ6zM1+o39YdL4+HiLuonCaGYd+OLnVH3d5PWkE9/5iLBLMZrGffXZ/HJqN1VBsFzzTY=
  - secure: RY3/4ys0u+gwuf4B+Nobx0MJCStfmg05jShb+k+T8dQJwhp/SXNFtDxLfENjzLmbgf3obCPIM3Ocw+B//GNV8qw1lLjVd3JWR3nD9O2hM3rfKxyCVDjVbd7Er6kOu/ZM2NQkwuw8w2SECXTuZtUk9E0c3TGyKxA6SMU5iP5RKUCELDN3GAQ0XAJs4VvkSEWeJTp65wbtoq9cVNJS22vUcjBaspTeQywiie6jsjBe65xkeB3Dqw2nWM00Sav5+4qTns/Wz4Qxm3bCdI0QDL9SbOEZGVvNCUj4Q5KnEfOqKrDuMOm6AOvzpO83hKKzBfmi99QtIRindHrt1B9AIUuJVMLJP0U0kcQox03YvdOm1A8QCSb08BSDZQydpiQ42y8sbzuwCf1yOEcfVYLxbsfVKvajEoa8/tWJADkmSLwgE+s0aT6UVPfSxgb+c21DOpNz9CdUL6T1kBrznaMpjak8Dhr5MuX1MGxE7WuZydS6ATnbOI5lymYbYAY+Iiq741X+S/+/HE9iywT/7+ksjN3twuw1fnm9mN0EuW/TIyosGtbWvphdL7qbHbcWeTpO5RqBD6A8jPzQvnYxQ6MKoTvBM3gB0IjseG5jX2Z6ddthVZhcfByUyA5ngAyuvdNONKbp3rZzB87jhIRPQgBcGouKu6hPGLYhrmC9vkJ4lT9BD74=
  - secure: FGssl6U+/y+8wf901cNNaokvdBxRHmfLPjuOkcmlgTth2jBcfC84b5Ny8F1bCHZAVaBdxFDeP6BDu073G6D21lUMJW2QPWr+gHjy6BFyYMR6fWiUK55Y/vhz0+vdwFZDDixG2Bp3R5mkQW44JkbjBaT6ZwVfJ7YAGimJFYyrPLkeBPrctETYBJorxohW9GxNI4kI1Q+RodQixUFbEHHRJ1GZ2UXLDP+Z01S2W+dAE6LtT2NOZ5u41iJLYEnwqTyvQZCPopiE+gVDJnuOr+qAMuYp8tL25vtSjCPR34qACf7/VU5Q2HFCQJz/0u511Yx49R3gQfGHw7nWjPKXbxWZJRRihJmzmaWlKvRUhgOEseRKZn50XObiu80P8c3Noi+RFYvFRJD6KoMM5SAeHd9ogFXoEyhOxJ4d1mPZG+Yk3ieVou2+cRVGy36ntIsLEXlSySoByFHM8BryINV+pPEyQoQ/9RaUUvToDRoKNny5DI0AijyJHxyFG41aCPKlcTtf2STkn8v0R9hZN76WuIU+hgzOK/ubnAyHim8sw+Eu8t8IDKjXDCc4OSVI119VZV0mSOoaZo+JpTvjio/MHzTwrUEhQojJxr4iFA1GoWAimaM4OSq8bRsrGEAlL00da5t5MF5gE3UtBoHQJoK/vylRQO/xL4PPSAt3u9B2u0hy3o0=
